package es.codeurjc.grupo12.scissors_please.config;

import es.codeurjc.grupo12.scissors_please.model.Bot;
import es.codeurjc.grupo12.scissors_please.model.Tournament;
import es.codeurjc.grupo12.scissors_please.model.User;
import es.codeurjc.grupo12.scissors_please.repository.BotRepository;
import es.codeurjc.grupo12.scissors_please.repository.TournamentRepository;
import es.codeurjc.grupo12.scissors_please.repository.UserRepository;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.password.PasswordEncoder;

@Configuration
@Slf4j
public class DataInitializer {

  @Bean
  public CommandLineRunner initData(
      UserRepository userRepository,
      BotRepository botRepository,
      TournamentRepository tournamentRepository,
      PasswordEncoder passwordEncoder) {
    return args -> {
      if (userRepository.count() == 0) {
        User adminUser = new User();
        adminUser.setUsername("admin");
        adminUser.setEmail("admin@scissors-please.com");
        adminUser.setPassword(passwordEncoder.encode("admin123"));
        adminUser.setRoles(List.of("ADMIN", "USER"));

        User regularUser = new User();
        regularUser.setUsername("user");
        regularUser.setEmail("user@scissors-please.com");
        regularUser.setPassword(passwordEncoder.encode("user123"));
        regularUser.setRoles(List.of("USER"));

        userRepository.save(adminUser);
        userRepository.save(regularUser);

        log.info("admin user created admin:admin123");
        log.info("ordinary user created user:user123");
      }

      if (tournamentRepository.count() == 0) {
        List<Tournament> tournaments = new ArrayList<>();
        String[] statuses = {"Upcoming", "In Progress", "Completed"};

        for (int i = 1; i <= 15; i++) {
          Tournament tournament = new Tournament();
          tournament.setName("Seed Tournament " + i);
          tournament.setStatus(statuses[(i - 1) % statuses.length]);
          tournament.setStartDate(LocalDate.now().plusDays(i));
          tournament.setDescription(
              "Autogenerated tournament "
                  + i
                  + " - Format: Single Elimination - "
                  + (16 + i)
                  + " slots");
          tournaments.add(tournament);
        }

        tournamentRepository.saveAll(tournaments);
        log.info("15 seed tournaments created");
      }

      if (botRepository.count() == 0) {
        List<User> owners =
            userRepository.findAll().stream()
                .filter(user -> user.getRoles() == null || !user.getRoles().contains("ADMIN"))
                .sorted(Comparator.comparing(User::getUsername))
                .toList();

        if (owners.isEmpty()) {
          log.warn("No non-admin users found. Skipping seed bot generation");
          return;
        }

        List<Bot> bots = new ArrayList<>();
        String[] languages = {"Python", "JavaScript", "Java"};

        for (int i = 1; i <= 15; i++) {
          User owner = owners.get((i - 1) % owners.size());

          Bot bot = new Bot();
          bot.setName("Seed Bot " + i);
          bot.setDescription("Autogenerated bot " + i + " with adaptive strategy");
          bot.setLanguage(languages[(i - 1) % languages.length]);
          bot.setCode("def move(history):\n    return 'rock'");
          bot.setImage("https://picsum.photos/seed/seed-bot-" + i + "/120");
          bot.setPublic(i % 3 != 0);
          bot.setElo(1000 + (i * 25));
          bot.setTags(List.of("seed", "auto", "bot-" + i));
          bot.setOwnerId(owner.getId());
          bots.add(bot);
        }

        botRepository.saveAll(bots);
        log.info("15 seed bots created");
      }
    };
  }
}
