package es.codeurjc.grupo12.scissors_please.config;

import es.codeurjc.grupo12.scissors_please.model.Tournament;
import es.codeurjc.grupo12.scissors_please.model.User;
import es.codeurjc.grupo12.scissors_please.repository.TournamentRepository;
import es.codeurjc.grupo12.scissors_please.repository.UserRepository;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.password.PasswordEncoder;

@Configuration
@Slf4j
public class DataInitializer {

  @Bean
  public CommandLineRunner initData(
      UserRepository userRepository,
      TournamentRepository tournamentRepository,
      PasswordEncoder passwordEncoder) {
    return args -> {
      if (userRepository.count() == 0) {
        User adminUser = new User();
        adminUser.setUsername("admin");
        adminUser.setEmail("admin@scissors-please.com");
        adminUser.setPassword(passwordEncoder.encode("admin123"));
        adminUser.setRoles(List.of("ADMIN", "USER"));

        User regularUser = new User();
        regularUser.setUsername("user");
        regularUser.setEmail("user@scissors-please.com");
        regularUser.setPassword(passwordEncoder.encode("user123"));
        regularUser.setRoles(List.of("USER"));

        userRepository.save(adminUser);
        userRepository.save(regularUser);

        log.info("admin user created admin:admin123");
        log.info("ordinary user created user:user123");
      }

      if (tournamentRepository.count() == 0) {
        List<Tournament> tournaments = new ArrayList<>();
        String[] statuses = {"Upcoming", "In Progress", "Completed"};

        for (int i = 1; i <= 15; i++) {
          Tournament tournament = new Tournament();
          tournament.setName("Seed Tournament " + i);
          tournament.setStatus(statuses[(i - 1) % statuses.length]);
          tournament.setStartDate(LocalDate.now().plusDays(i));
          tournament.setDescription(
              "Autogenerated tournament "
                  + i
                  + " - Format: Single Elimination - "
                  + (16 + i)
                  + " slots");
          tournaments.add(tournament);
        }

        tournamentRepository.saveAll(tournaments);
        log.info("15 seed tournaments created");
      }
    };
  }
}
