package es.codeurjc.grupo12.scissors_please.config;

import es.codeurjc.grupo12.scissors_please.model.Bot;
import es.codeurjc.grupo12.scissors_please.model.Match;
import es.codeurjc.grupo12.scissors_please.model.Tournament;
import es.codeurjc.grupo12.scissors_please.model.User;
import es.codeurjc.grupo12.scissors_please.repository.BotRepository;
import es.codeurjc.grupo12.scissors_please.repository.MatchRepository;
import es.codeurjc.grupo12.scissors_please.repository.TournamentRepository;
import es.codeurjc.grupo12.scissors_please.repository.UserRepository;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.password.PasswordEncoder;

@Configuration
@Slf4j
public class DataInitializer {

  private static final int SEEDED_REGULAR_USERS = 48;
  private static final int BOTS_PER_USER = 2;
  private static final Pattern SLOT_PATTERN =
      Pattern.compile("(\\d+)\\s+slots", Pattern.CASE_INSENSITIVE);

  @Bean
  public CommandLineRunner initData(
      UserRepository userRepository,
      BotRepository botRepository,
      MatchRepository matchRepository,
      TournamentRepository tournamentRepository,
      PasswordEncoder passwordEncoder) {
    return args -> {
      if (userRepository.count() == 0) {
        List<User> users = new ArrayList<>();

        User adminUser = new User();
        adminUser.setUsername("admin");
        adminUser.setEmail("admin@scissors-please.com");
        adminUser.setPassword(passwordEncoder.encode("admin123"));
        adminUser.setBlocked(false);
        adminUser.setRoles(List.of("ADMIN", "USER"));
        users.add(adminUser);

        User regularUser = new User();
        regularUser.setUsername("user");
        regularUser.setEmail("user@scissors-please.com");
        regularUser.setPassword(passwordEncoder.encode("user123"));
        regularUser.setBlocked(false);
        regularUser.setRoles(List.of("USER"));
        users.add(regularUser);

        for (int i = 1; i <= SEEDED_REGULAR_USERS; i++) {
          User seededUser = new User();
          seededUser.setUsername("seed_user_" + i);
          seededUser.setEmail("seed_user_" + i + "@scissors-please.com");
          seededUser.setCreatedAt(generateRandomDateIn2026());
          seededUser.setPassword(passwordEncoder.encode("user123"));
          seededUser.setRoles(List.of("USER"));
          users.add(seededUser);
        }

        userRepository.saveAll(users);

        log.info("admin user created admin:admin123");
        log.info("ordinary user created user:user123");
        log.info("{} additional seed users created", SEEDED_REGULAR_USERS);
      }

      if (tournamentRepository.count() == 0) {
        List<Tournament> tournaments = new ArrayList<>();
        int[] slotsPerTournament = {32, 32, 16, 8, 8, 16, 16, 8, 32, 16, 8, 32, 16, 8, 32};

        for (int i = 1; i <= slotsPerTournament.length; i++) {
          int slots = slotsPerTournament[i - 1];
          Tournament tournament = new Tournament();
          tournament.setName("Seed Tournament " + i);
          tournament.setSlots(slots);
          tournament.setStatus("Upcoming");
          tournament.setStartDate(LocalDate.now().plusDays(i));
          tournament.setDescription(
              "Autogenerated tournament "
                  + i
                  + " - Format: Single Elimination - "
                  + slots
                  + " slots");

          tournament.setMatches(new ArrayList<>());
          tournament.setParticipants(new ArrayList<>());
          tournaments.add(tournament);
        }

        tournamentRepository.saveAll(tournaments);
        log.info("{} seed tournaments created (with 32/16/8 slots)", slotsPerTournament.length);
      }

      if (botRepository.count() == 0) {
        List<User> owners =
            userRepository.findAll().stream()
                .filter(user -> user.getRoles() == null || !user.getRoles().contains("ADMIN"))
                .sorted(Comparator.comparing(User::getUsername))
                .toList();

        if (owners.isEmpty()) {
          log.warn("No non-admin users found. Skipping seed bot generation");
          return;
        }

        List<Bot> bots = new ArrayList<>();
        String[] languages = {"Python", "JavaScript", "Java"};
        int botIndex = 1;

        for (User owner : owners) {
          for (int i = 1; i <= BOTS_PER_USER; i++) {
            Bot bot = new Bot();
            bot.setName(owner.getUsername() + " Bot " + i);
            bot.setDescription(
                "Autogenerated bot " + botIndex + " for user " + owner.getUsername());
            bot.setLanguage(languages[(botIndex - 1) % languages.length]);
            bot.setCode("def move(history):\n    return 'rock'");
            bot.setPublic(true);
            bot.setElo(1000 + (botIndex * 10));
            bot.setTags(List.of("seed", "auto", "bot-" + botIndex));
            bot.setOwnerId(owner.getId());
            bots.add(bot);
            botIndex++;
          }
        }

        botRepository.saveAll(bots);
        log.info("{} seed bots created ({} per user)", bots.size(), BOTS_PER_USER);
      }

      assignParticipantsToTournaments(tournamentRepository, botRepository);

      if (matchRepository.count() == 0) {
        List<Bot> bots = botRepository.findAll();
        if (bots.size() < 2) {
          log.warn("Not enough bots found. Skipping seed match generation");
          return;
        }

        List<Match> matches = new ArrayList<>();
        LocalDateTime baseTimestamp = LocalDateTime.now();

        for (int i = 1; i <= 18; i++) {
          Bot bot1 = bots.get((i - 1) % bots.size());
          Bot bot2 = bots.get(i % bots.size());

          int bot1Score = (i % 3) + 1;
          int bot2Score = ((i + 1) % 3) + 1;
          String result;

          if (i % 5 == 0) {
            bot1Score = 2;
            bot2Score = 2;
            result = "Draw";
          } else if (bot1Score > bot2Score) {
            result = "Win";
          } else {
            result = "Loss";
          }

          Match match = new Match();
          match.setBot1(bot1);
          match.setBot2(bot2);
          match.setBot1Score(bot1Score);
          match.setBot2Score(bot2Score);
          match.setResult(result);
          match.setTimestamp(baseTimestamp.minusMinutes(i * 15L));
          match.setRounds(new ArrayList<>());
          matches.add(match);
        }

        matchRepository.saveAll(matches);
        log.info("18 seed matches created");
      }
    };
  }

  private void assignParticipantsToTournaments(
      TournamentRepository tournamentRepository, BotRepository botRepository) {
    List<Tournament> tournaments =
        tournamentRepository.findAll().stream()
            .sorted(Comparator.comparing(Tournament::getId))
            .toList();
    List<Bot> bots =
        botRepository.findAll().stream().sorted(Comparator.comparing(Bot::getId)).toList();

    if (tournaments.isEmpty() || bots.isEmpty()) {
      return;
    }

    List<Tournament> updatedTournaments = new ArrayList<>();
    int cursor = 0;

    for (Tournament tournament : tournaments) {
      int slots = extractSlotsFromDescription(tournament.getDescription());
      if (slots <= 0) {
        continue;
      }

      int remainingBots = bots.size() - cursor;
      if (remainingBots < 2) {
        break;
      }

      if (remainingBots < slots) {
        continue;
      }

      int participantsCount = slots;
      List<Bot> participants = new ArrayList<>(bots.subList(cursor, cursor + participantsCount));
      cursor += participantsCount;

      tournament.setParticipants(participants);
      updatedTournaments.add(tournament);
    }

    if (!updatedTournaments.isEmpty()) {
      tournamentRepository.saveAll(updatedTournaments);
      log.info(
          "{} tournaments populated with participants (32/16/8 ready)", updatedTournaments.size());
    }
  }

  private int extractSlotsFromDescription(String description) {
    if (description == null || description.isBlank()) {
      return 0;
    }

    Matcher matcher = SLOT_PATTERN.matcher(description);
    if (!matcher.find()) {
      return 0;
    }

    try {
      return Integer.parseInt(matcher.group(1));
    } catch (NumberFormatException ex) {
      return 0;
    }
  }
  // Just for testing
  private LocalDateTime generateRandomDateIn2026() {
    long startEpochDay = LocalDate.of(2026, Month.JANUARY, 1).toEpochDay();
    long endEpochDay = LocalDate.of(2026, Month.DECEMBER, 31).toEpochDay();

    long randomDay = ThreadLocalRandom.current().nextLong(startEpochDay, endEpochDay);

    int hour = ThreadLocalRandom.current().nextInt(0, 24);
    int minute = ThreadLocalRandom.current().nextInt(0, 60);

    return LocalDate.ofEpochDay(randomDay).atTime(hour, minute);
  }
}
