# HTTPS Profile Configuration
server.port=${SERVER_PORT:8443}
server.http.port=${SERVER_HTTP_PORT:8080}
server.ssl.enabled=true
server.ssl.key-store=${SERVER_SSL_KEY_STORE:classpath:keystore.p12}
server.ssl.key-store-password=${SERVER_SSL_KEY_STORE_PASSWORD:password}
