spring.application.name="Scissors, Please!"
spring.profiles.active=@spring.profiles.active@

# Logging Configuration
logging.level.root=INFO
logging.level.es.codeurjc.grupo12.scissors_please=DEBUG
logging.level.org.springframework.security=WARN
logging.level.org.springframework.web=WARN

# Mustache Configuration
spring.mustache.prefix=classpath:/templates/
spring.mustache.suffix=.html